name: Trigger auto deployment for leimvnwebcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/leimvnwebcontainerapp-AutoDeployTrigger-dc30f5d6-a836-48ef-b2b7-edba35373772.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LEIMVNWEBCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LEIMVNWEBCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LEIMVNWEBCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: leimvnweacr.azurecr.io
          registryUsername: ${{ secrets.LEIMVNWEBCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LEIMVNWEBCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: leimvnwebcontainerapp
          resourceGroup: leimvnweb
          imageToBuild: leimvnweacr.azurecr.io/leimvnwebcontainerapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


